volume: harpoon-volume # this needs to match the volume name passed to the podman run command
targets:
- name: demo
  url: http://github.com/cooktheryan/harpoon-demo
  raw:
    targetPath: raw
    schedule: "*/1 * * * *"
    pullImage: false
  branch: main
